---
- name: Install Ruby Bundler
  hosts: app
  become: true
  tasks:
    - name: Install ruby, bundler
      apt:
       update_cache: yes
       name: "{{ item }}"
       state: present
      loop:
         - ruby-full
         - ruby-bundler
         - build-essential
